
package complaint_management_system;

import static complaint_management_system.db.mycon;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;


/**
 *
 * @author Babygirl
 */
public class forgotPassword extends javax.swing.JFrame {
Connection conn = null;
    /**
     * Creates new form Register
     */
    public forgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JPanel();
        user3 = new javax.swing.JLabel();
        reg2 = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Newuser = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        ftxtregwork = new javax.swing.JTextField();
        ftxtsanswer = new javax.swing.JTextField();
        user6 = new javax.swing.JLabel();
        user7 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        fquiz = new javax.swing.JTextField();
        fpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Register.setBackground(new java.awt.Color(102, 102, 102));
        Register.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        user3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        user3.setForeground(new java.awt.Color(255, 255, 255));
        user3.setText("Password");

        reg2.setBackground(new java.awt.Color(204, 0, 0));
        reg2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        reg2.setForeground(new java.awt.Color(255, 255, 255));
        reg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint_management_system/icons/cancel.png"))); // NOI18N
        reg2.setText("Cancel");
        reg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg2ActionPerformed(evt);
            }
        });

        reg.setBackground(new java.awt.Color(0, 0, 255));
        reg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        reg.setForeground(new java.awt.Color(255, 255, 255));
        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint_management_system/icons/regis.png"))); // NOI18N
        reg.setText("Save");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Newuser.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Newuser.setForeground(new java.awt.Color(255, 255, 255));
        Newuser.setText("Forgot password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(Newuser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Newuser)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        user4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        user4.setForeground(new java.awt.Color(255, 255, 255));
        user4.setText("Reg/Work number");

        ftxtregwork.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ftxtregwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtregworkActionPerformed(evt);
            }
        });

        ftxtsanswer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ftxtsanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtsanswerActionPerformed(evt);
            }
        });

        user6.setBackground(new java.awt.Color(255, 255, 255));
        user6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        user6.setForeground(new java.awt.Color(255, 255, 255));
        user6.setText("Security Question");

        user7.setBackground(new java.awt.Color(255, 255, 255));
        user7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        user7.setForeground(new java.awt.Color(255, 255, 255));
        user7.setText("Security Answer");

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint_management_system/icons/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        fquiz.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fquiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fquizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterLayout.createSequentialGroup()
                                .addComponent(user4)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtregwork, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(search))
                            .addGroup(RegisterLayout.createSequentialGroup()
                                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user3))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftxtsanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fquiz, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(RegisterLayout.createSequentialGroup()
                                            .addComponent(reg)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(reg2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(fpass, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user4)
                    .addComponent(ftxtregwork, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user6)
                    .addComponent(fquiz, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user7)
                    .addComponent(ftxtsanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fpass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed

        String RegWorkNumber= ftxtregwork.getText();
        String secA  = ftxtsanswer.getText();
        String pass = fpass.getText();
         try{  
         Statement s = db.mycon().createStatement();
         ResultSet rs= s.executeQuery("select *FROM user WHERE RegWorkNumber='"+RegWorkNumber+"' AND securityAnswer='"+secA+"'");
        
         if(rs.next())
         {
          s.executeUpdate("update user set password='"+pass+"' WHERE  RegWorkNumber='"+RegWorkNumber+"' AND securityAnswer='"+secA+"'");
         JOptionPane.showMessageDialog(null,"Your password is sucessfully reset");
             setVisible(false);
             dispose();
            Login lg = new Login();
            lg.setVisible(true);  
            
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            // Get the size of the frame
            Dimension frameSize = lg.getSize();
            // Calculate the coordinates to center the frame
            int x = (screenSize.width - frameSize.width) / 2;
            int y = (screenSize.height - frameSize.height) ;
            // Set the frame's location
            lg.setLocation(x, y);
            this.setVisible(false);
         }
         else 
             JOptionPane.showMessageDialog(null,"Please enter correct answer");
         }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in connection");
        }
        
        
    }//GEN-LAST:event_regActionPerformed

    private void reg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_reg2ActionPerformed

    private void ftxtregworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtregworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtregworkActionPerformed

    private void ftxtsanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtsanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtsanswerActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String sql="Select * from user where RegWorkNumber=?";
        try{
            PreparedStatement st = mycon().prepareStatement(sql);
            st.setString(1, ftxtregwork.getText());
            ResultSet res = st.executeQuery();

            if(res.next()){
                String add1=res.getString("RegWorkNumber");
                ftxtregwork.setText(add1);

                String add2=res.getString("securityQuestion");
                fquiz.setText(add2);

                

            }else{
                Component rootPane = null;
                JOptionPane.showMessageDialog(rootPane, "Enter The Correct Registration or Work Number");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void fquizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fquizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fquizActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Newuser;
    private javax.swing.JPanel Register;
    private javax.swing.JPasswordField fpass;
    private javax.swing.JTextField fquiz;
    private javax.swing.JTextField ftxtregwork;
    private javax.swing.JTextField ftxtsanswer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reg;
    private javax.swing.JButton reg2;
    private javax.swing.JButton search;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user6;
    private javax.swing.JLabel user7;
    // End of variables declaration//GEN-END:variables

}